### PR TITLE
some compile errors on Ububtu 20

### PR DESCRIPTION
**Pull request by drowe67**
@tmiw I had some compile errors on Ubuntu 20. Can you please tell me if this builds OK for you on OSX?

### CODE REVIEW

**Comment by drowe67** [comment]
@tmiw - I tried this PR with codec2, and everything built and the ctests ran OK.  I had to modify unitest/CMakeLists.txt:

```
-   GIT_REPOSITORY https://github.com/tmiw/cml.git
+   GIT_REPOSITORY https://github.com/drowe67/cml.git
+   GIT_TAG dr-errors
```

I haven't checked that in, thought I would wait until we see if this PR builds OK for you on OSX.  I've sent an invite for you for this repo so you can commit directly.

**Comment by tmiw** [comment]
> @tmiw - I tried this PR with codec2, and everything built and the ctests ran OK. I had to modify unitest/CMakeLists.txt:
> 
> ```
> -   GIT_REPOSITORY https://github.com/tmiw/cml.git
> +   GIT_REPOSITORY https://github.com/drowe67/cml.git
> +   GIT_TAG dr-errors
> ```
> 
> I haven't checked that in, thought I would wait until we see if this PR builds OK for you on OSX. I've sent an invite for you for this repo so you can commit directly.

Doesn't compile here:

```
ConvEncode.cpp:115:13: error: no matching function for call to 'mxCalcSingleSubscript'
                                index = mxCalcSingleSubscript(GENENCODER, 2, subs);
                                        ^~~~~~~~~~~~~~~~~~~~~
/opt/local/include/octave-6.4.0/octave/mexproto.h:296:30: note: candidate function not viable: no known conversion from 'long [2]' to 'mwIndex *' (aka 'long long *') for 3rd argument
extern OCTINTERP_API mwIndex mxCalcSingleSubscript (const mxArray *ptr,
                             ^
1 error generated.
```

I'm running Octave 6.4.0 here (or at least that's what MacPorts claims it is). Looks like we may want to use "mwIndex" instead of "int" or "long long" for `subs` to ensure we use the correct type regardless of version of Octave?

**Comment by tmiw** [comment]
With the change I just pushed, codec2 ctests build and pass 100%. 👍

**Comment by drowe67** [comment]
That's great - works for me on my local Ubuntu 20 machine - thanks @tmiw :+1:

**Pull request merged**
